#! /usr/bin/env python
# -*- python -*-
# Generated by PAGE version 4.0
# In conjuction with Tcl version 8.6
#    Jul. 15, 2013 10:13:28 AM
import sys

py2 = py30 = py31 = False
version = sys.hexversion
if version >= 0x020600F0 and version < 0x03000000 :
    py2 = True    # Python 2.6 or 2.7
    from Tkinter import *
    import ttk
elif version >= 0x03000000 and version < 0x03010000 :
    py30 = True
    from tkinter import *
    import ttk
elif version >= 0x03010000:
    py31 = True
    from tkinter import *
    import tkinter.ttk as ttk
else:
    print ("""
    You do not have a version of python supporting ttk widgets..
    You need a version >= 2.6 to execute PAGE modules.
    """)
    sys.exit()



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('New_Toplevel_1')
    root.geometry('1167x864+1744+211')
    set_Tk_var()
    w = New_Toplevel_1 (root)
    init()
    root.mainloop()

w = None
def create_New_Toplevel_1 (root):
    '''Starting point when module is imported by another program.'''
    global w, w_win
    if w: # So we have only one instance of window.
        return
    w = Toplevel (root)
    w.title('New_Toplevel_1')
    w.geometry('1167x864+1744+211')
    set_Tk_var()
    w_win = New_Toplevel_1 (w)
    init()
    return w_win

def destroy_New_Toplevel_1 ():
    global w
    w.destroy()
    w = None


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global che67
    che67 = StringVar()

    global che69
    che69 = StringVar()

    global che72
    che72 = StringVar()

    global spinbox
    spinbox = StringVar()


def init():
    pass



def TODO():
        print ('TODO')
        sys.stdout.flush()


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        TkFixedFont = "-family monospace -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
        TkMenuFont = "-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"

        self.master = master
        self.Canvas1 = Canvas (master)
        self.Canvas1.place(relx=0.28,rely=0.02,relheight=0.96,relwidth=0.7)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=814)

        self.menubar = Menu(master,font=TkMenuFont,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.menubar.add_separator(
                background="#d9d9d9")
        self.newcascade = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.newcascade,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                font=TkMenuFont,
                foreground="#000000",
                label="NewCascade")
        self.newcascade.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=TODO,
                font=TkMenuFont,
                foreground="#000000",
                label="NewCommand")

        self.Frame1 = Frame (master)
        self.Frame1.place(relx=0.02,rely=0.02,relheight=0.12,relwidth=0.25)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(width=295)

        self.Entry1 = Entry (self.Frame1)
        self.Entry1.place(relx=0.07,rely=0.1,relheight=0.19,relwidth=0.87)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font=TkFixedFont)
        self.Entry1.configure(width=256)

        self.Button1 = Button (self.Frame1)
        self.Button1.place(relx=0.07,rely=0.48,height=26,width=68)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Button''')

        self.Radiobutton4 = Radiobutton (self.Frame1)
        self.Radiobutton4.place(relx=0.61,rely=0.38,relheight=0.19
                ,relwidth=0.21)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(text='''Radio''')

        self.Radiobutton5 = Radiobutton (self.Frame1)
        self.Radiobutton5.place(relx=0.61,rely=0.67,relheight=0.19
                ,relwidth=0.21)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(text='''Radio''')

        self.Frame2 = Frame (master)
        self.Frame2.place(relx=0.02,rely=0.17,relheight=0.16,relwidth=0.25)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(width=295)

        self.Radiobutton1 = Radiobutton (self.Frame2)
        self.Radiobutton1.place(relx=0.03,rely=0.3,relheight=0.15,relwidth=0.21)

        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(text='''Radio''')

        self.Radiobutton2 = Radiobutton (self.Frame2)
        self.Radiobutton2.place(relx=0.03,rely=0.52,relheight=0.15
                ,relwidth=0.21)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(text='''Radio''')

        self.Radiobutton3 = Radiobutton (self.Frame2)
        self.Radiobutton3.place(relx=0.03,rely=0.74,relheight=0.15
                ,relwidth=0.21)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(text='''Radio''')

        self.Label1 = Label (self.Frame2)
        self.Label1.place(relx=0.1,rely=0.07,height=18,width=26)
        self.Label1.configure(text='''BCL''')

        self.Label2 = Label (self.Frame2)
        self.Label2.place(relx=0.58,rely=0.07,height=18,width=77)
        self.Label2.configure(text='''Beat''')
        self.Label2.configure(width=77)

        self.Spinbox1 = Spinbox (self.Frame2,from_=1.0,to=100.0)
        self.Spinbox1.place(relx=0.61,rely=0.3,relheight=0.15,relwidth=0.2)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(from_="1.0")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(textvariable=spinbox)
        self.Spinbox1.configure(to="100.0")
        self.Spinbox1.configure(width=58)

        self.Checkbutton1 = Checkbutton (self.Frame2)
        self.Checkbutton1.place(relx=0.58,rely=0.52,relheight=0.15
                ,relwidth=0.21)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(text='''Check''')
        self.Checkbutton1.configure(variable=che67)

        self.Frame3 = Frame (master)
        self.Frame3.place(relx=0.02,rely=0.35,relheight=0.18,relwidth=0.25)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(width=295)

        self.Checkbutton2 = Checkbutton (self.Frame3)
        self.Checkbutton2.place(relx=0.03,rely=0.19,relheight=0.13
                ,relwidth=0.28)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(text='''Check''')
        self.Checkbutton2.configure(variable=che69)
        self.Checkbutton2.configure(width=83)

        self.Checkbutton3 = Checkbutton (self.Frame3)
        self.Checkbutton3.place(relx=0.07,rely=0.52,relheight=0.13
                ,relwidth=0.21)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(text='''Check''')
        self.Checkbutton3.configure(variable=che72)

        self.Radiobutton6 = Radiobutton (self.Frame3)
        self.Radiobutton6.place(relx=0.75,rely=0.06,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton6.configure(activebackground="#d9d9d9")
        self.Radiobutton6.configure(text='''Radio''')

        self.Radiobutton7 = Radiobutton (self.Frame3)
        self.Radiobutton7.place(relx=0.75,rely=0.19,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton7.configure(activebackground="#d9d9d9")
        self.Radiobutton7.configure(text='''Radio''')

        self.Radiobutton8 = Radiobutton (self.Frame3)
        self.Radiobutton8.place(relx=0.75,rely=0.32,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton8.configure(activebackground="#d9d9d9")
        self.Radiobutton8.configure(text='''Radio''')

        self.Radiobutton9 = Radiobutton (self.Frame3)
        self.Radiobutton9.place(relx=0.75,rely=0.45,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton9.configure(activebackground="#d9d9d9")
        self.Radiobutton9.configure(text='''Radio''')

        self.Radiobutton10 = Radiobutton (self.Frame3)
        self.Radiobutton10.place(relx=0.75,rely=0.58,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton10.configure(activebackground="#d9d9d9")
        self.Radiobutton10.configure(text='''Radio''')

        self.Radiobutton11 = Radiobutton (self.Frame3)
        self.Radiobutton11.place(relx=0.75,rely=0.71,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton11.configure(activebackground="#d9d9d9")
        self.Radiobutton11.configure(text='''Radio''')

        self.Radiobutton12 = Radiobutton (self.Frame3)
        self.Radiobutton12.place(relx=0.75,rely=0.84,relheight=0.13
                ,relwidth=0.21)
        self.Radiobutton12.configure(activebackground="#d9d9d9")
        self.Radiobutton12.configure(text='''Radio''')







if __name__ == '__main__':
    vp_start_gui()

