#!/bin/bash
## runtime=30s
##

function checkpoint {
    save traces
}
    
function clean {
    rm -rf stdOut data traces snapshot.0*
}

function run {
    beginTest
    clean
    runBinary cardioid object.data tt06*.fit.data tt06*.sv >| stdOut 2>&1
    ./traceVoltage.py $(sed -e 's/^/-g /' sensor.txt) >| traces
    numCompare traces 1e-14 >| result 2>&1
    endTest
}
