for x in PM_LSU_FIN PM_ST_FIN PM_LSU_FX_FIN PM_LSU_LDX PM_LD_CMPL PM_VSU0_2FLOP PM_VSU1_2FLOP PM_VSU0_4FLOP PM_VSU1_4FLOP PM_FLOP PM_FLOP_SUM_VEC PM_FXU0_FIN PM_FXU1_FIN PM_VSU0_FIN PM_VSU1_FIN PM_RUN_INST_CMPL PM_RUN_CYC
do
	grep $x tmp.out
done 
