#!/bin/bash
## runtime=0s

function checkpoint {
    save state
}
    
function clean {
    rm -rf snapshot.000000000002 state data
}

function run {
    beginTest
    rm -f restart
    ln -s snapshot.000000000001/restart .
    runBinary cardioid
    tail -n +20 snapshot.000000000002/state#000000 >| state
    numCompare state 1e-14 >| result 2>&1
    endTest
}
