#! /bin/csh
cd oomph

bin/regenerate_config_files.sh .
set build_dir = $PWD/build
if (-e $build_dir) then
   echo "$build_dir exists"
else
   mkdir build
endif

set lib_dir = $PWD/../../lib
set configure_options = '--enable-suppress-doc --enable-MPI --with-blas="$lib_dir/libmkl_peloton.a" --with-lapack="$lib_dir/libmkl_peloton.a" CXX=/usr/local/bin/mpig++ CC=/usr/local/bin/mpigcc'

echo "Running ./configure --prefix $build_dir $configure_options"
/bin/sh -c "./configure --prefix $build_dir $configure_options"
echo "done running ./configure"

make
make install
