#!/bin/bash
## runtime=0s
## tags=seq

function checkpoint {
    save data
}
    
function clean {
    rm -rf stdOut data snapshot.0*
}

function run {
    beginTest
    clean
    rm -f data
    runBinary cardioid object.data tt06.fit.data >| stdOut 2>&1 
    numCompare data 1e-14 >| result 2>&1
    endTest
}
