#!/bin/bash
## runtime=0s
## tags=seq

function checkpoint {
    save data
}
    
function clean {
    rm -f stdOut data
}

function run {
    beginTest
    rm -f data
    runBinary cardioid >| stdOut 2>&1 
    numCompare data 1e-14 >| result 2>&1
    endTest
}
