/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i singleCellOptions.ggo -F singleCellOptions 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "singleCellOptions.h"

const char *gengetopt_args_info_purpose = "Run a single cell simulation";

const char *gengetopt_args_info_usage = "Usage: cardiodSingleCell [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "This program runs a single cell simulation of Vm' = -Iion.";

const char *gengetopt_args_info_help[] = {
  "      --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -o, --object=STRING           Object file",
  "  -m, --method=STRING           Method name (or module name)",
  "  -r, --reaction-name=STRING    Name of reaction in object file",
  "  -h, --dt=DOUBLE               Timestep for the simulation  (default=`0.020')",
  "  -d, --duration=DOUBLE         Duration of the simulation",
  "  -S, --save-state-file=STRING  Filename to save the state to",
  "  -T, --save-state-time=DOUBLE  Time to save the state",
  "  -p, --output-dt=DOUBLE        Output timetep  (default=`1')",
  "  -c, --add-column=STRING       Add a column of output",
  "  -A, --add-all-state           Add all possible states to the output\n                                  (default=off)",
  "  -H, --add-header              Add a header row to stdout  (default=off)",
  "  -C, --clamp-file=STRING       Clamp variables according to an input file",
  "  -n, --s1-count=INT            Number of s1 stimulii  (default=`1')",
  "  -b, --s1-bcl=DOUBLE           Basic cycle length  (default=`1000')",
  "  -f, --s1-offset=DOUBLE        Time to start s1 stimulii  (default=`0')",
  "  -s, --stim-at=DOUBLE          Stimulate at the following time in ms",
  "  -a, --stim-strength=DOUBLE    Strength of the stimulus  (default=`60')",
  "  -t, --stim-duration=DOUBLE    Duration of the stimulus  (default=`1')",
  "  -N, --num-points=INT          Number of points to stimulate  (default=`1')",
  "  -U, --alternate-update        Use updateGates/nonGates formulation.\n                                  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->object_given = 0 ;
  args_info->method_given = 0 ;
  args_info->reaction_name_given = 0 ;
  args_info->dt_given = 0 ;
  args_info->duration_given = 0 ;
  args_info->save_state_file_given = 0 ;
  args_info->save_state_time_given = 0 ;
  args_info->output_dt_given = 0 ;
  args_info->add_column_given = 0 ;
  args_info->add_all_state_given = 0 ;
  args_info->add_header_given = 0 ;
  args_info->clamp_file_given = 0 ;
  args_info->s1_count_given = 0 ;
  args_info->s1_bcl_given = 0 ;
  args_info->s1_offset_given = 0 ;
  args_info->stim_at_given = 0 ;
  args_info->stim_strength_given = 0 ;
  args_info->stim_duration_given = 0 ;
  args_info->num_points_given = 0 ;
  args_info->alternate_update_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->object_arg = NULL;
  args_info->object_orig = NULL;
  args_info->method_arg = NULL;
  args_info->method_orig = NULL;
  args_info->reaction_name_arg = NULL;
  args_info->reaction_name_orig = NULL;
  args_info->dt_arg = 0.020;
  args_info->dt_orig = NULL;
  args_info->duration_orig = NULL;
  args_info->save_state_file_arg = NULL;
  args_info->save_state_file_orig = NULL;
  args_info->save_state_time_orig = NULL;
  args_info->output_dt_arg = 1;
  args_info->output_dt_orig = NULL;
  args_info->add_column_arg = NULL;
  args_info->add_column_orig = NULL;
  args_info->add_all_state_flag = 0;
  args_info->add_header_flag = 0;
  args_info->clamp_file_arg = NULL;
  args_info->clamp_file_orig = NULL;
  args_info->s1_count_arg = 1;
  args_info->s1_count_orig = NULL;
  args_info->s1_bcl_arg = 1000;
  args_info->s1_bcl_orig = NULL;
  args_info->s1_offset_arg = 0;
  args_info->s1_offset_orig = NULL;
  args_info->stim_at_arg = NULL;
  args_info->stim_at_orig = NULL;
  args_info->stim_strength_arg = 60;
  args_info->stim_strength_orig = NULL;
  args_info->stim_duration_arg = 1;
  args_info->stim_duration_orig = NULL;
  args_info->num_points_arg = 1;
  args_info->num_points_orig = NULL;
  args_info->alternate_update_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->object_help = gengetopt_args_info_help[2] ;
  args_info->object_min = 0;
  args_info->object_max = 0;
  args_info->method_help = gengetopt_args_info_help[3] ;
  args_info->reaction_name_help = gengetopt_args_info_help[4] ;
  args_info->dt_help = gengetopt_args_info_help[5] ;
  args_info->duration_help = gengetopt_args_info_help[6] ;
  args_info->save_state_file_help = gengetopt_args_info_help[7] ;
  args_info->save_state_time_help = gengetopt_args_info_help[8] ;
  args_info->output_dt_help = gengetopt_args_info_help[9] ;
  args_info->add_column_help = gengetopt_args_info_help[10] ;
  args_info->add_column_min = 0;
  args_info->add_column_max = 0;
  args_info->add_all_state_help = gengetopt_args_info_help[11] ;
  args_info->add_header_help = gengetopt_args_info_help[12] ;
  args_info->clamp_file_help = gengetopt_args_info_help[13] ;
  args_info->s1_count_help = gengetopt_args_info_help[14] ;
  args_info->s1_bcl_help = gengetopt_args_info_help[15] ;
  args_info->s1_offset_help = gengetopt_args_info_help[16] ;
  args_info->stim_at_help = gengetopt_args_info_help[17] ;
  args_info->stim_at_min = 0;
  args_info->stim_at_max = 0;
  args_info->stim_strength_help = gengetopt_args_info_help[18] ;
  args_info->stim_duration_help = gengetopt_args_info_help[19] ;
  args_info->num_points_help = gengetopt_args_info_help[20] ;
  args_info->alternate_update_help = gengetopt_args_info_help[21] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    double double_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}

static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_multiple_string_field (args_info->object_given, &(args_info->object_arg), &(args_info->object_orig));
  free_string_field (&(args_info->method_arg));
  free_string_field (&(args_info->method_orig));
  free_string_field (&(args_info->reaction_name_arg));
  free_string_field (&(args_info->reaction_name_orig));
  free_string_field (&(args_info->dt_orig));
  free_string_field (&(args_info->duration_orig));
  free_string_field (&(args_info->save_state_file_arg));
  free_string_field (&(args_info->save_state_file_orig));
  free_string_field (&(args_info->save_state_time_orig));
  free_string_field (&(args_info->output_dt_orig));
  free_multiple_string_field (args_info->add_column_given, &(args_info->add_column_arg), &(args_info->add_column_orig));
  free_string_field (&(args_info->clamp_file_arg));
  free_string_field (&(args_info->clamp_file_orig));
  free_string_field (&(args_info->s1_count_orig));
  free_string_field (&(args_info->s1_bcl_orig));
  free_string_field (&(args_info->s1_offset_orig));
  free_multiple_field (args_info->stim_at_given, (void *)(args_info->stim_at_arg), &(args_info->stim_at_orig));
  args_info->stim_at_arg = 0;
  free_string_field (&(args_info->stim_strength_orig));
  free_string_field (&(args_info->stim_duration_orig));
  free_string_field (&(args_info->num_points_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  write_multiple_into_file(outfile, args_info->object_given, "object", args_info->object_orig, 0);
  if (args_info->method_given)
    write_into_file(outfile, "method", args_info->method_orig, 0);
  if (args_info->reaction_name_given)
    write_into_file(outfile, "reaction-name", args_info->reaction_name_orig, 0);
  if (args_info->dt_given)
    write_into_file(outfile, "dt", args_info->dt_orig, 0);
  if (args_info->duration_given)
    write_into_file(outfile, "duration", args_info->duration_orig, 0);
  if (args_info->save_state_file_given)
    write_into_file(outfile, "save-state-file", args_info->save_state_file_orig, 0);
  if (args_info->save_state_time_given)
    write_into_file(outfile, "save-state-time", args_info->save_state_time_orig, 0);
  if (args_info->output_dt_given)
    write_into_file(outfile, "output-dt", args_info->output_dt_orig, 0);
  write_multiple_into_file(outfile, args_info->add_column_given, "add-column", args_info->add_column_orig, 0);
  if (args_info->add_all_state_given)
    write_into_file(outfile, "add-all-state", 0, 0 );
  if (args_info->add_header_given)
    write_into_file(outfile, "add-header", 0, 0 );
  if (args_info->clamp_file_given)
    write_into_file(outfile, "clamp-file", args_info->clamp_file_orig, 0);
  if (args_info->s1_count_given)
    write_into_file(outfile, "s1-count", args_info->s1_count_orig, 0);
  if (args_info->s1_bcl_given)
    write_into_file(outfile, "s1-bcl", args_info->s1_bcl_orig, 0);
  if (args_info->s1_offset_given)
    write_into_file(outfile, "s1-offset", args_info->s1_offset_orig, 0);
  write_multiple_into_file(outfile, args_info->stim_at_given, "stim-at", args_info->stim_at_orig, 0);
  if (args_info->stim_strength_given)
    write_into_file(outfile, "stim-strength", args_info->stim_strength_orig, 0);
  if (args_info->stim_duration_given)
    write_into_file(outfile, "stim-duration", args_info->stim_duration_orig, 0);
  if (args_info->num_points_given)
    write_into_file(outfile, "num-points", args_info->num_points_orig, 0);
  if (args_info->alternate_update_given)
    write_into_file(outfile, "alternate-update", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->object_given, args_info->object_min, args_info->object_max, "'--object' ('-o')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->add_column_given, args_info->add_column_min, args_info->add_column_max, "'--add-column' ('-c')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->stim_at_given, args_info->stim_at_min, args_info->stim_at_max, "'--stim-at' ('-s')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_DOUBLE:
      *((double **)field) = (double *)realloc (*((double **)field), (field_given + prev_given) * sizeof (double)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_DOUBLE:
          (*((double **)field))[i + field_given] = tmp->arg.double_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_DOUBLE:
        if (! *((double **)field)) {
          *((double **)field) = (double *)malloc (sizeof (double));
          (*((double **)field))[0] = default_value->double_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * object_list = NULL;
  struct generic_list * add_column_list = NULL;
  struct generic_list * stim_at_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "object",	1, NULL, 'o' },
        { "method",	1, NULL, 'm' },
        { "reaction-name",	1, NULL, 'r' },
        { "dt",	1, NULL, 'h' },
        { "duration",	1, NULL, 'd' },
        { "save-state-file",	1, NULL, 'S' },
        { "save-state-time",	1, NULL, 'T' },
        { "output-dt",	1, NULL, 'p' },
        { "add-column",	1, NULL, 'c' },
        { "add-all-state",	0, NULL, 'A' },
        { "add-header",	0, NULL, 'H' },
        { "clamp-file",	1, NULL, 'C' },
        { "s1-count",	1, NULL, 'n' },
        { "s1-bcl",	1, NULL, 'b' },
        { "s1-offset",	1, NULL, 'f' },
        { "stim-at",	1, NULL, 's' },
        { "stim-strength",	1, NULL, 'a' },
        { "stim-duration",	1, NULL, 't' },
        { "num-points",	1, NULL, 'N' },
        { "alternate-update",	0, NULL, 'U' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "Vo:m:r:h:d:S:T:p:c:AHC:n:b:f:s:a:t:N:U", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'o':	/* Object file.  */
        
          if (update_multiple_arg_temp(&object_list, 
              &(local_args_info.object_given), optarg, 0, 0, ARG_STRING,
              "object", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Method name (or module name).  */
        
        
          if (update_arg( (void *)&(args_info->method_arg), 
               &(args_info->method_orig), &(args_info->method_given),
              &(local_args_info.method_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "method", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Name of reaction in object file.  */
        
        
          if (update_arg( (void *)&(args_info->reaction_name_arg), 
               &(args_info->reaction_name_orig), &(args_info->reaction_name_given),
              &(local_args_info.reaction_name_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "reaction-name", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'h':	/* Timestep for the simulation.  */
        
        
          if (update_arg( (void *)&(args_info->dt_arg), 
               &(args_info->dt_orig), &(args_info->dt_given),
              &(local_args_info.dt_given), optarg, 0, "0.020", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "dt", 'h',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Duration of the simulation.  */
        
        
          if (update_arg( (void *)&(args_info->duration_arg), 
               &(args_info->duration_orig), &(args_info->duration_given),
              &(local_args_info.duration_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "duration", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Filename to save the state to.  */
        
        
          if (update_arg( (void *)&(args_info->save_state_file_arg), 
               &(args_info->save_state_file_orig), &(args_info->save_state_file_given),
              &(local_args_info.save_state_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "save-state-file", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Time to save the state.  */
        
        
          if (update_arg( (void *)&(args_info->save_state_time_arg), 
               &(args_info->save_state_time_orig), &(args_info->save_state_time_given),
              &(local_args_info.save_state_time_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "save-state-time", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Output timetep.  */
        
        
          if (update_arg( (void *)&(args_info->output_dt_arg), 
               &(args_info->output_dt_orig), &(args_info->output_dt_given),
              &(local_args_info.output_dt_given), optarg, 0, "1", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "output-dt", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Add a column of output.  */
        
          if (update_multiple_arg_temp(&add_column_list, 
              &(local_args_info.add_column_given), optarg, 0, 0, ARG_STRING,
              "add-column", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'A':	/* Add all possible states to the output.  */
        
        
          if (update_arg((void *)&(args_info->add_all_state_flag), 0, &(args_info->add_all_state_given),
              &(local_args_info.add_all_state_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "add-all-state", 'A',
              additional_error))
            goto failure;
        
          break;
        case 'H':	/* Add a header row to stdout.  */
        
        
          if (update_arg((void *)&(args_info->add_header_flag), 0, &(args_info->add_header_given),
              &(local_args_info.add_header_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "add-header", 'H',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* Clamp variables according to an input file.  */
        
        
          if (update_arg( (void *)&(args_info->clamp_file_arg), 
               &(args_info->clamp_file_orig), &(args_info->clamp_file_given),
              &(local_args_info.clamp_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "clamp-file", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of s1 stimulii.  */
        
        
          if (update_arg( (void *)&(args_info->s1_count_arg), 
               &(args_info->s1_count_orig), &(args_info->s1_count_given),
              &(local_args_info.s1_count_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "s1-count", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Basic cycle length.  */
        
        
          if (update_arg( (void *)&(args_info->s1_bcl_arg), 
               &(args_info->s1_bcl_orig), &(args_info->s1_bcl_given),
              &(local_args_info.s1_bcl_given), optarg, 0, "1000", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "s1-bcl", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Time to start s1 stimulii.  */
        
        
          if (update_arg( (void *)&(args_info->s1_offset_arg), 
               &(args_info->s1_offset_orig), &(args_info->s1_offset_given),
              &(local_args_info.s1_offset_given), optarg, 0, "0", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "s1-offset", 'f',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Stimulate at the following time in ms.  */
        
          if (update_multiple_arg_temp(&stim_at_list, 
              &(local_args_info.stim_at_given), optarg, 0, 0, ARG_DOUBLE,
              "stim-at", 's',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Strength of the stimulus.  */
        
        
          if (update_arg( (void *)&(args_info->stim_strength_arg), 
               &(args_info->stim_strength_orig), &(args_info->stim_strength_given),
              &(local_args_info.stim_strength_given), optarg, 0, "60", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "stim-strength", 'a',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Duration of the stimulus.  */
        
        
          if (update_arg( (void *)&(args_info->stim_duration_arg), 
               &(args_info->stim_duration_orig), &(args_info->stim_duration_given),
              &(local_args_info.stim_duration_given), optarg, 0, "1", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "stim-duration", 't',
              additional_error))
            goto failure;
        
          break;
        case 'N':	/* Number of points to stimulate.  */
        
        
          if (update_arg( (void *)&(args_info->num_points_arg), 
               &(args_info->num_points_orig), &(args_info->num_points_given),
              &(local_args_info.num_points_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-points", 'N',
              additional_error))
            goto failure;
        
          break;
        case 'U':	/* Use updateGates/nonGates formulation..  */
        
        
          if (update_arg((void *)&(args_info->alternate_update_flag), 0, &(args_info->alternate_update_given),
              &(local_args_info.alternate_update_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "alternate-update", 'U',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "help") == 0) {
            cmdline_parser_print_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->object_arg),
    &(args_info->object_orig), args_info->object_given,
    local_args_info.object_given, 0,
    ARG_STRING, object_list);
  update_multiple_arg((void *)&(args_info->add_column_arg),
    &(args_info->add_column_orig), args_info->add_column_given,
    local_args_info.add_column_given, 0,
    ARG_STRING, add_column_list);
  update_multiple_arg((void *)&(args_info->stim_at_arg),
    &(args_info->stim_at_orig), args_info->stim_at_given,
    local_args_info.stim_at_given, 0,
    ARG_DOUBLE, stim_at_list);

  args_info->object_given += local_args_info.object_given;
  local_args_info.object_given = 0;
  args_info->add_column_given += local_args_info.add_column_given;
  local_args_info.add_column_given = 0;
  args_info->stim_at_given += local_args_info.stim_at_given;
  local_args_info.stim_at_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (object_list, 1 );
  free_list (add_column_list, 1 );
  free_list (stim_at_list, 0 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
