#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -R "span[ptile=4]"
#BSUB -R "affinity[core(5):distribute=pack]"
#BSUB -n 4
#BSUB -x
#BSUB -G guests
#BSUB -q pdebug
#BSUB -W 15
#---------------------------------------
export BIND_THREADS=yes
export OMP_NUM_THREADS=1
ulimit -s 10240
mpirun -mxm -np 4  ../../../bin/ray-openmp/cardioid
#mpirun -mxm -np 4  ../../bin/cardioid-ray-openmp 
#mpirun -np 1 nvprof -o cardioid-cuda-tl.%q{OMPI_COMM_WORLD_RANK}.nvprof ../../bin/cardioid-ray-openmp 
